import type { Metadata } from "next";
import { Inter } from 'next/font/google'

import ProvideSession from "@/components/providers/session_provider";
import { auth } from "@/lib/auth";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" suppressHydrationWarning data-theme="nord">
      <body
        className={` antialiased`}
      >
        {/* <ThemeProvider
            attribute="data-theme"
            themes={[
            'solarized-dark',
            'solarized-light',
            'monokai',
            'atom-one-light',
            'atom-one-dark',
            'everforest-dark',
            'everforest-light',
            'tokyo-night',
            'catppuccin',
            'nord'
            ]}
            defaultTheme="nord"
            enableSystem
            disableTransitionOnChange
        > */}
          <ProvideSession session={session}>
            {children}
          </ProvideSession>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
