import type { Metadata } from "next";
import ProvideSession from "@/components/providers/session_provider";
import { auth } from "@/lib/auth";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" suppressHydrationWarning data-theme="nord">
      <body
        className={` antialiased`}
      >
          <ProvideSession session={session}>
              {children}
          </ProvideSession>
        <script
        dangerouslySetInnerHTML={{
          __html: `
            (() => {
              const theme = localStorage.getItem("theme");
              if (theme) {
                document.body.setAttribute("data-theme", theme);
              }
            });
          `
        }}
      />
      </body>
    </html>
  );
}
